# Generated by Django 2.1.2 on 2018-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181011_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
